# Generated by Django 4.2.6 on 2023-11-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0002_alter_customuser_address_alter_customuser_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Введите имя')),
                ('image', models.ImageField(upload_to='', verbose_name='Загрузите фото')),
            ],
        ),
    ]
