# Generated by Django 4.2.6 on 2023-11-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0003_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Введите имя'),
        ),
    ]
